name: technology_config
description: This plant produces hydrogen using water electrolysis powered by a solar-PV system
technologies:
  solar:
    performance_model:
      model: PYSAMSolarPlantPerformanceModel
    cost_model:
      model: ATBUtilityPVCostModel
    model_inputs:
      performance_parameters:
        pv_capacity_kWdc: 400000
        dc_ac_ratio: 1.34
        create_model_from: new
        tilt_angle_setting: lat-func
        pysam_options:
          SystemDesign:
            gcr: 0.3
            array_type: 2
            bifaciality: 0.65
            inv_eff: 96.0
            losses: 14.6
            module_type: 1
            azimuth: 180
            rotlim: 45
          SolarResource:
            albedo_default: 0.2
      cost_parameters:
        capex_per_kWac: 1367  # 2022 costs from ATB 2024 v3
        opex_per_kWac_per_year: 24  # 2022 costs from ATB 2024 v3
        cost_year: 2022
  electrolyzer:
    performance_model:
      model: ECOElectrolyzerPerformanceModel
    cost_model:
      model: CustomElectrolyzerCostModel
    model_inputs:
      performance_parameters:
        size_mode: normal
        n_clusters: 18
        cluster_rating_MW: 10
        eol_eff_percent_loss: 10  # eol defined as x% change in efficiency from bol
        uptime_hours_until_eol: 80000.  # number of 'on' hours until electrolyzer reaches eol
        include_degradation_penalty: true  # include degradation
        turndown_ratio: 0.1  # turndown_ratio = minimum_cluster_power/cluster_rating_MW
        location: onshore
        electrolyzer_capex: 1295  # unused in the performance model if pem_control_type is 'basic' but required as an input
      cost_parameters:
        capex_USD_per_kW: 1000.0
        fixed_om_USD_per_kW_per_year: 12.8
        cost_year: 2022
      financial_parameters:
        capital_items:
          depr_period: 7
          replacement_cost_percent: 0.15  # percent of capex - H2A default case
