name: driver_config
description: This analysis runs a wind plant from Ard, a solar plant from pysam, and a simple battery
general:
  folder_output: windard_pv_battery
driver:
  optimization:
    flag: false
    solver: COBYLA
    tol: 0.1
    catol: 15000
    max_iter: 100
    rhobeg: 2
    debug_print: true
design_variables:
  wind:
    spacing_primary:
      flag: true
      lower: 3.0
      upper: 20.0
      units: null
    spacing_secondary:
      flag: true
      lower: 3.0
      upper: 20.0
      units: null
    angle_orientation:
      flag: true
      lower: -180.0
      upper: 180.0
      units: deg
    angle_skew:
      flag: true
      lower: -75.0
      upper: 180.0
      units: deg
    x_substations:
      flag: true
      lower: -3000
      upper: 3000
      units: m
      scaler: 1.0e-2
    y_substations:
      flag: true
      lower: -3000
      upper: 3000
      units: m
      scaler: 1.0e-2
constraints:
  wind:
    boundary_distances:
      flag: true
      units: km
      upper: 0.0
    turbine_spacing:
      flag: true
      units: km
      lower: 0.552
objective:
  name: finance_subgroup_dispatched_electricity.LCOE
recorder:
  flag: true
  file: wind_h2_opt.sql
  includes: ['*']
  excludes: ['*_resource_data']
